CAR_BRANDS=(
    ('Audi', 'Audi'),
    ('BMW', 'BMW'),
    ('Chevrolet', 'Chevrolet'),
    ('Citroen', 'Citroen'),
    ('Fiat', 'Fiat'),
    ('Ford', 'Ford'),
    ('Honda', 'Honda'),
    ('Hyundai', 'Hyundai'),
    ('Kia', 'Kia'),
    ('Mazda', 'Mazda'),
    ('Mercedes', 'Mercedes'),
    ('Mitsubishi', 'Mitsubishi'),
    ('Nissan', 'Nissan'),
    ('Opel', 'Opel'),
    ('Peugeot', 'Peugeot'),
    ('Renault', 'Renault'),
    ('Seat', 'Seat'),
    ('Skoda', 'Skoda'),
    ('Suzuki', 'Suzuki'),
    ('Toyota', 'Toyota'),
    ('Volkswagen', 'Volkswagen'),
    ('Volvo', 'Volvo'),
    ('Porsche', 'Porsche'),
)

TRANSMISSION=(
    ('Automatic', 'Automatic'),
    ('Manual', 'Manual'),
    ('Semi-Automatic', 'Semi-Automatic'),
)